### ISSUE TITLE
Not compatible with ZTE MF289F

### ISSUE THREAD

**Issue by 1zun4** [SpeckyYT/zte-cpe#3]
Hey. Your library is the only thing I found so far for ZTE, but it seems not to be compatible with the `ZTE MF289F`. I looked into it as I was starting to write my own library, and I think the problem here too is the fact that they do not simply base64 the password.

The password is encoded differently. To my surprise it at least prints out the IMEI, but without the login it doesn't work as expected.

**Comment by SpeckyYT** [comment]
Hello. Sadly I don't think I'll buy another ZTE router, since I'm not even using the first one I've got anymore. So the chances of me fixing the login method is really low.

If you're able to understand how the passwords are hashed and you're still able to use this library for it, feel free to make a PR. Otherwise just make your own library if the version of the router you've got is just too different from this library.

Good luck.

**Comment by 1zun4** [comment]
Since I'm not really a Node.js developer, I have written a library for the ZTE MF289F in Rust: [zte-cpe-rs](https://github.com/1zun4/zte-cpe-rs).

Regarding the login process, you can check the relevant code [here](https://github.com/1zun4/zte-cpe-rs/blob/b16b210c3467f1680afb457336123b4039acfb68/src/lib.rs#L44-L64).

To log in on the ZTM MF289F, we first need to SHA256 the password, and then SHA256 the concatenated HASH_PASSWORD and LD, which generates the valid password. I’m not sure why they chose this method, but they spend a lot of time to make it more obscure.
